sudo: required

services:
  -docker

before_install:
  - docker build -t jays81/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true jays81/react-test npm test

after_success:
  - docker build -t jays81/multi-client ./client
  - docker build -t jays81/multi-nginx ./nginx
  - docker build -t jays81/multi-server ./server
  - docker build -t jays81/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jays81/multi-client
  - docker push jays81/multi-nginx
  - docker push jays81/multi-server
  - docker push jays81/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-454515840781"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
